# .github/actions/publish-release/action.yml
name: "Publish GitHub Release"
description: "Create or update a GitHub Release and upload all artifacts."
inputs:
  version:
    description: "The release tag/version to publish (e.g., v1.2.3)"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create or update Release
      shell: bash
      run: |
        set -euo pipefail
        : "${GH_TOKEN:?GH_TOKEN is required}"
        gh release view "${{ inputs.version }}" >/dev/null 2>&1 || \
          gh release create "${{ inputs.version }}" \
            --title "Release ${{ inputs.version }}" \
            --notes "Automated release for ${{ inputs.version }}"

    - name: Upload all assets
      shell: bash
      run: |
        set -euo pipefail
        shopt -s nullglob
        files=(artifacts/**/*)
        if [ ${#files[@]} -eq 0 ]; then
          echo "No artifacts to upload; skipping."
          exit 0
        fi
        for file in "${files[@]}"; do
          gh release upload "${{ inputs.version }}" "$file" \
            --clobber --name "$(basename "$file")"
        done
