name = "Titus"
uuid = "161ade51-a71e-4c5f-b262-f1262fd3217d"
authors = ["Nathan-Wamsley"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
