name = "Pioneer"
uuid = "585db54e-1982-41c9-ae07-9e9eb56c7d61"
authors = ["Natahan Wamsley"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
