name: Precompile Data Cache & Download
description: >
  Caches & (on cache-miss) downloads the Zenodo precompile data into temp/zenodo.

inputs:
  cache-key:
    description: "A static key to version the cache (bump when Zenodo files change)"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Restore or save cache
      id: cache
      uses: actions/cache@v3
      with:
        path: temp/zenodo
        key: ${{ inputs.cache-key }}
        restore-keys: |
          ${{ inputs.cache-key }}

    - name: Download precompile data (if cache miss)
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p temp/zenodo
        cd temp/zenodo
        curl -LJO https://zenodo.org/record/16289168/files/yeast.poin.zip?download=1
        unzip yeast.poin.zip
        for i in 1 2; do
          curl -L "https://zenodo.org/record/16289168/files/20241211_bkc_25-0856_Goldfarb_Wamsley_Yeast_Alternating-v2_3min_Rep${i}.arrow?download=1" \
            -o yeast_${i}.arrow
        done
