name: "Prune Unneeded Files"
description: "Remove locale data, versioned .so files, and strip symbols from the built app tree."
inputs:
  app_root:
    description: "Path to the compiled app root (e.g. build/Pioneer_<id>/Applications/Pioneer)"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Trim unneeded files
      shell: bash
      run: |
        ROOT="${{ inputs.app_root }}"

        # Remove all locale translation files
        find "$ROOT/share/julia/artifacts" \
          -type d -name locale -prune \
          -exec rm -rf {} +

        # Strip debug symbols (optional)
        find "$ROOT/lib/julia" \
          -type f -name '*.so' \
          -exec strip --strip-unneeded {} + || true

        # Remove man pages
        find "$ROOT/share/julia/artifacts" \
          -type d -path '*/share/man*' -prune \
          -exec rm -rf {} +

        # Remove HTML docs
        find "$ROOT/share/julia/artifacts" \
          -type d -path '*/share/doc*' -prune \
          -exec rm -rf {} +

        # Remove fontconfig configuration & fonts
        find "$ROOT/etc/fonts"               -type d -prune -exec rm -rf {} +
        find "$ROOT/share/fontconfig"        -type d -prune -exec rm -rf {} +
        find "$ROOT/share/julia/artifacts"   -type d -path '*/fonts' -prune -exec rm -rf {} +

        # Remove any broken symlinks
        find "$ROOT/lib/julia" -xtype l -delete
