name: "Determine Version"
description: "Set VERSION output from tag name, workflow_dispatch input, or default to 0.0.0."
inputs:
  tag-input:
    description: "Manual tag override (from workflow_dispatch)"
    required: false
    type: string

runs:
  using: "composite"
  outputs:
    version:
      description: "Resolved version string"
      value: ${{ steps.determine.outputs.VERSION }}
  steps:
    - id: determine
      name: Determine VERSION
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ inputs.tag-input }}" ]]; then
          echo "VERSION=${{ inputs.tag-input }}" >> "$GITHUB_OUTPUT"
        elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
        else
          echo "VERSION=0.0.0" >> "$GITHUB_OUTPUT"
        fi
