name: Build App
on:
  push:
    branches:
      - main
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos
            runner: macos-latest
            arch: x64
            identifier: macos-x64
          #- os: macos
          #  runner: macos-latest
          #  arch: arm64
          #  identifier: macos-arm64
          #- os: windows
          #  runner: windows-latest
          #  arch: x64
          #  identifier: windows-x64
          #- os: linux
          #  runner: ubuntu-latest
          #  arch: x64
          #  identifier: linux-x64
    steps:
      - uses: actions/checkout@v4
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
      
      - name: Install the Apple certificate and provisioning profile
        if: matrix.os == 'macos'
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERT_P12 }}
          P12_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
          INSTALLER_CERT_BASE64: ${{ secrets.MACOS_INSTALLER_CERT_P12 }}
          INSTALLER_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
          NOTARIZE_APPLE_ID: ${{ secrets.NOTARIZE_APPLE_ID }}
          NOTARIZE_PASSWORD: ${{ secrets.NOTARIZE_PASSWORD }}
          NOTARIZE_TEAM_ID: ${{ secrets.NOTARIZE_TEAM_ID }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          INSTALLER_CERT_PATH=$RUNNER_TEMP/installer_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          echo -n "$INSTALLER_CERT_BASE64" | base64 --decode -o $INSTALLER_CERT_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $INSTALLER_CERT_PATH -P "$INSTALLER_CERT_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # login keychain so signing tools can locate the certificate
          security list-keychains -d user -s $KEYCHAIN_PATH login.keychain

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - uses: apple-actions/import-codesign-certs@v2
        if: matrix.os == 'macos'
        with:
          p12-file-base64: ${{ secrets.MACOS_CERT_P12 }}
          p12-password: ${{ secrets.MACOS_CERT_PASSWORD }}
          keychain-password: ${{ secrets.MACOS_CERT_PASSWORD }}
          keychain: signing_temp

      - uses: apple-actions/import-codesign-certs@v2
        if: matrix.os == 'macos'
        with:
          p12-file-base64: ${{ secrets.MACOS_INSTALLER_CERT_P12 }}
          p12-password: ${{ secrets.MACOS_CERT_PASSWORD }}
          keychain-password: ${{ secrets.MACOS_CERT_PASSWORD }}
          keychain: signing_temp
          create-keychain: false

      - name: List codesigning identities
        if: matrix.os == 'macos'
        run: 
          security find-identity -v -p codesigning
          security find-identity -v -p basic

      - name: Install dependencies
        run: |
          julia --project=. -e 'using Pkg; Pkg.add("PackageCompiler"); Pkg.instantiate()'
          
      - name: Compile application
        run: |
          julia --project=. -e '
            using PackageCompiler;
            create_app(".", "build/Pioneer_${{ matrix.identifier }}/Applications/Pioneer/", incremental=false, force=true,
              executables=["SearchDIA" => "main_SearchDIA", "BuildSpecLib" => "main_BuildSpecLib", "GetSearchParams" => "main_GetSearchParams", "GetBuildLibParams" => "main_GetBuildLibParams", "convertMzML" => "main_convertMzML", "ParseSpecLib" => "main_ParseSpecLib"]);
          '
      - name: Codesign and package macOS app
        if: matrix.os == 'macos'
        env:
          CODESIGN_IDENTITY: ${{ secrets.CODESIGN_IDENTITY }}
          PKG_SIGN_IDENTITY: ${{ secrets.PKG_SIGN_IDENTITY }}
        run: |
          APPNAME="Pioneer"
          DIST="build/Pioneer_${{ matrix.identifier }}/Applications/Pioneer"
          PKGROOT="pkgroot"
          VERSION=$(grep -m1 '^version' Project.toml | awk -F'"' '{print $2}')

          rm -rf "$PKGROOT"
          mkdir -p "$PKGROOT/usr/local/$APPNAME"
          cp -R "$DIST"/* "$PKGROOT/usr/local/$APPNAME/"

          echo "Codesigning binaries"
          while IFS= read -r -d '' file; do
            if file "$file" | grep -q 'Mach-O'; then
              codesign --verbose=4 --force --options runtime --timestamp \
                --entitlements src/build/entitlements.plist \
                --sign "$CODESIGN_IDENTITY" "$file"
            fi
          done < <(find "$PKGROOT/usr/local/$APPNAME" -type f -print0)

          pkgbuild --root "$PKGROOT" \
            --identifier com.example.pioneer \
            --version "$VERSION" \
            --install-location / PioneerUnsigned.pkg
          productsign --sign "$PKG_SIGN_IDENTITY" \
            PioneerUnsigned.pkg PioneerInstaller.pkg
          rm PioneerUnsigned.pkg

      - name: Notarize macOS package
        if: matrix.os == 'macos'
        env:
          AC_USERNAME: ${{ secrets.NOTARIZE_APPLE_ID }}
          AC_PASSWORD: ${{ secrets.NOTARIZE_PASSWORD }}
          TEAM_ID: ${{ secrets.NOTARIZE_TEAM_ID }}
        run: |
          xcrun notarytool store-credentials notary-profile \
            --apple-id "$AC_USERNAME" \
            --team-id "$TEAM_ID" \
            --password "$AC_PASSWORD"
          result=$(xcrun notarytool submit PioneerInstaller.pkg \
            --keychain-profile notary-profile --wait --output-format json)
          echo "$result"
          status=$(echo "$result" | grep -o '"status" *: *"[^" ]*"' | head -n1 | sed 's/.*"status" *: *"\([^"]*\)"/\1/')
          subid=$(echo "$result" | grep -o '"id" *: *"[^" ]*"' | head -n1 | sed 's/.*"id" *: *"\([^"]*\)"/\1/')
          if [ "$status" != "Accepted" ]; then
            echo "Notarization failed with status $status"
            xcrun notarytool log "$subid" --keychain-profile notary-profile
            exit 1
          fi

      - name: Staple notarization ticket
        if: matrix.os == 'macos'
        run: |
          xcrun stapler staple PioneerInstaller.pkg
      
      
      - name: Package Windows MSI
        if: matrix.os == 'windows'
        shell: pwsh
        run: |
          &"${env:WIX}\bin\candle.exe" src\build\windows\installer.wxs
          &"${env:WIX}\bin\light.exe" installer.wixobj -o PioneerInstaller.msi
      
      - name: Package Linux .deb
        if: matrix.os == 'linux'
        run: |
          mkdir -p deb/usr/local/Pioneer
          cp -r build/Pioneer_${{ matrix.identifier }}/Applications/Pioneer/* deb/usr/local/Pioneer/
          dpkg-deb --build deb PioneerInstaller.deb
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pioneer-${{ matrix.identifier }}
          path: |
            PioneerInstaller.pkg
            PioneerInstaller.msi
            PioneerInstaller.deb

