name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia ${{ matrix.version }} on ${{ matrix.os }} (${{ github.event_name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        version: ['1.11']
        os:      [ubuntu-latest]
        arch:    [x64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch:    ${{ matrix.arch }}

      - name: Cache Julia packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.julia/registries
            ~/.julia/packages
          key: julia-${{ matrix.version }}-${{ runner.os }}-${{ hashFiles('**/Project.toml','**/Manifest.toml') }}
          restore-keys: |
            julia-${{ matrix.version }}-${{ runner.os }}-

      - name: Instantiate & build
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.build()'

      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.test()'

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  docs:
    if: github.ref == 'refs/heads/main'
    name: Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'

      - name: Cache docs packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.julia/registries
            ~/.julia/packages
          key: docs-${{ runner.os }}-${{ hashFiles('docs/Project.toml','docs/Manifest.toml') }}

      - name: Configure doc environment
        shell: julia --project=docs --color=yes {0}
        run: |
          using Pkg
          Pkg.develop(path=pwd())
          Pkg.instantiate()

      - name: Build docs
        uses: julia-actions/julia-buildpkg@v1

      - name: Deploy docs
        uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN:    ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY:  ${{ secrets.DOCUMENTER_KEY }}

      - name: Run doctests
        shell: julia --project=docs --color=yes {0}
        run: |
          using Documenter: DocMeta, doctest
          using Pioneer
          DocMeta.setdocmeta!(Pioneer, :DocTestSetup, :(using Pioneer); recursive=true)
          doctest(Pioneer)
