name: Register

on:
  issue_comment:
    types:
      - created
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  Registrator:
    if: github.event_name == 'workflow_dispatch' || github.event.comment.body == '@JuliaRegistries/Registrator register'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/Registrator.jl@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
