name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia ${{ matrix.version }} on ${{ matrix.os }} (${{ github.event_name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        version: ['1.11']
        os:      [ubuntu-latest]
        arch:    [x64]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch:    ${{ matrix.arch }}

      - name: Cache Julia packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.julia/registries
            ~/.julia/packages
          key: julia-${{ matrix.version }}-${{ runner.os }}-${{ hashFiles('**/Project.toml','**/Manifest.toml') }}
          restore-keys: |
            julia-${{ matrix.version }}-${{ runner.os }}-

      - name: Instantiate & build
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.build()'

      - name: Run tests
        run: julia --code-coverage=all --project=. -e 'using Pkg; Pkg.test(coverage=true)'

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  
